#!/bin/bash

for file in files/*; do
    
    filename=$(basename "$file")
    
    first_letter="${filename:0:1}"

    target_folder=$(echo "$first_letter" | tr '[:upper:]' '[:lower:]')
        
    mv "$file" "$first_letter/"
    
done